version: "3.9"

services:
  app-dev:
    image: bolt-ai:development
    build:
      context: .
      dockerfile: Dockerfile
      target: bolt-ai-development
    env_file: ".env.local"
    environment:
      - NODE_ENV=development
      - VITE_HMR_PROTOCOL=ws
      - VITE_HMR_HOST=localhost
      - VITE_HMR_PORT=5173
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - PORT=5173
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HuggingFace_API_KEY=${HuggingFace_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - GEMINI_LOGO_CREATOR_API_KEY=${GEMINI_LOGO_CREATOR_API_KEY}
      - OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL}
      - XAI_API_KEY=${XAI_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - TOGETHER_API_BASE_URL=${TOGETHER_API_BASE_URL}
      - AWS_BEDROCK_CONFIG=${AWS_BEDROCK_CONFIG}
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-debug}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
      - RUNNING_IN_DOCKER=true
            # 🔑 Google Generative AI Keys
      - GOOGLE_GENERATIVE_AI_API_KEY_1=${GOOGLE_GENERATIVE_AI_API_KEY_1}
      - GOOGLE_GENERATIVE_AI_API_KEY_2=${GOOGLE_GENERATIVE_AI_API_KEY_2}
      - GOOGLE_GENERATIVE_AI_API_KEY_3=${GOOGLE_GENERATIVE_AI_API_KEY_3}
      - GOOGLE_GENERATIVE_AI_API_KEY_4=${GOOGLE_GENERATIVE_AI_API_KEY_4}
      - GOOGLE_GENERATIVE_AI_API_KEY_5=${GOOGLE_GENERATIVE_AI_API_KEY_5}
      - GOOGLE_GENERATIVE_AI_API_KEY_6=${GOOGLE_GENERATIVE_AI_API_KEY_6}
      - GOOGLE_GENERATIVE_AI_API_KEY_7=${GOOGLE_GENERATIVE_AI_API_KEY_7}
      - GOOGLE_GENERATIVE_AI_API_KEY_8=${GOOGLE_GENERATIVE_AI_API_KEY_8}
      - GOOGLE_GENERATIVE_AI_API_KEY_9=${GOOGLE_GENERATIVE_AI_API_KEY_9}
      - GOOGLE_GENERATIVE_AI_API_KEY_10=${GOOGLE_GENERATIVE_AI_API_KEY_10}
      - GOOGLE_GENERATIVE_AI_API_KEY_11=${GOOGLE_GENERATIVE_AI_API_KEY_11}
      - GOOGLE_GENERATIVE_AI_API_KEY_12=${GOOGLE_GENERATIVE_AI_API_KEY_12}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app:cached
      - /app/node_modules
    ports:
      - "3000:3000"
    command: pnpm run dev --host 0.0.0.0
