name: main-new-frontend-workflow

on:
  push:
    branches:
      - main-new

jobs:
  ci-cd:
    runs-on: [vibe-coding-1]  # Self-hosted runner label

    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      HuggingFace_API_KEY: ${{ secrets.HuggingFace_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
      GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
      OLLAMA_API_BASE_URL: ${{ secrets.OLLAMA_API_BASE_URL }}
      XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
      TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
      TOGETHER_API_BASE_URL: ${{ secrets.TOGETHER_API_BASE_URL }}
      AWS_BEDROCK_CONFIG: ${{ secrets.AWS_BEDROCK_CONFIG }}
      VITE_LOG_LEVEL: debug
      DEFAULT_NUM_CTX: 32768
      # 🔑 Add your Google Generative AI Keys
      GOOGLE_GENERATIVE_AI_API_KEY_1: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY_1 }}
      GOOGLE_GENERATIVE_AI_API_KEY_2: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY_2 }}
      GOOGLE_GENERATIVE_AI_API_KEY_3: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY_3 }}
      GOOGLE_GENERATIVE_AI_API_KEY_4: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY_4 }}
      GOOGLE_GENERATIVE_AI_API_KEY_5: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY_5 }}
      GOOGLE_GENERATIVE_AI_API_KEY_6: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY_6 }}
      GOOGLE_GENERATIVE_AI_API_KEY_7: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY_7 }}
      GOOGLE_GENERATIVE_AI_API_KEY_8: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY_8 }}
      GOOGLE_GENERATIVE_AI_API_KEY_9: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY_9 }}
      GOOGLE_GENERATIVE_AI_API_KEY_10: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY_10 }}
      GOOGLE_GENERATIVE_AI_API_KEY_11: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY_11 }}
      GOOGLE_GENERATIVE_AI_API_KEY_12: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY_12 }}

    steps:
      - name: Fix Permissions Early
        run: sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Run with Docker Compose
        run: docker compose -f docker-compose.yaml up --build -d app-dev

      - name: Wait for App to Start (optional)
        run: sleep 10

      - name: Check if App is Running
        run: curl http://localhost:5173 || echo "App may still be starting"

      - name: Reset Permissions After Run
        run: sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work
