name: main-new-frontend-workflow

on:
  push:
    branches:
      - main-new

jobs:
  ci-cd:
    runs-on: [vibe-coding-1]  # Self-hosted runner label

    env:
      # Pass all required secrets/environment vars for Docker Compose
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      HuggingFace_API_KEY: ${{ secrets.HuggingFace_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
      GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
      OLLAMA_API_BASE_URL: ${{ secrets.OLLAMA_API_BASE_URL }}
      XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
      TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
      TOGETHER_API_BASE_URL: ${{ secrets.TOGETHER_API_BASE_URL }}
      AWS_BEDROCK_CONFIG: ${{ secrets.AWS_BEDROCK_CONFIG }}
      VITE_LOG_LEVEL: debug
      DEFAULT_NUM_CTX: 32768

    steps:
      - name: Clean workspace
        run: |
          sudo chown -R $USER:$USER .
          sudo rm -rf ./* || true
          sudo rm -rf ./.* || true

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set permissions
        run: |
          sudo chown -R $USER:$USER .
          sudo chmod -R 755 .

      - name: Build and Run with Docker Compose
        run: docker compose -f docker-compose.yaml up --build -d app-dev

      - name: Wait for App to Start (optional)
        run: sleep 10

      - name: Check if App is Running
        run: curl http://localhost:5173 || echo "App may still be starting"
