name: main-new-frontend-workflow

on:
  push:
    branches:
      - main-new

jobs:
  ci-cd:
    runs-on: [vibe-coding-1]  # Self-hosted runner label

    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      HuggingFace_API_KEY: ${{ secrets.HuggingFace_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
      GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
      OLLAMA_API_BASE_URL: ${{ secrets.OLLAMA_API_BASE_URL }}
      XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
      TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
      TOGETHER_API_BASE_URL: ${{ secrets.TOGETHER_API_BASE_URL }}
      AWS_BEDROCK_CONFIG: ${{ secrets.AWS_BEDROCK_CONFIG }}
      VITE_LOG_LEVEL: debug
      DEFAULT_NUM_CTX: 32768

    steps:
      - name: Fix Permissions Early
        run: sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Enable Docker BuildKit
        run: "echo '{ \"features\": { \"buildkit\": true } }' | sudo tee /etc/docker/daemon.json && sudo systemctl restart docker"


      - name: Build and Run with BuildKit Caching
        run: |
          export DOCKER_BUILDKIT=1
          docker compose -f docker-compose.yaml build --progress=plain
          docker compose -f docker-compose.yaml up -d app-dev

      - name: Wait for App to Start
        run: sleep 10

      - name: Check if App is Running
        run: curl http://localhost:5173 || echo "App may still be starting"

      - name: Reset Permissions After Run
        run: sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work
